baseURL = 'https://eng.d2iq.com/'
title = 'D2iQ Engineering'
Description = 'Insides from D2iQ Engineers'
theme = "casperv5"
languageCode = "en-us"

copyright = "© {{ YEAR }} D2iQ, Inc. All Rights Reserved."
enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
removePathAccents = true
disableKinds = [ "taxonomy" ]
ignoreErrors = ["error-disable-taxonomy"]

[permalinks]
  posts = '/blog/:slug/'
  tags = '/blog/tags/:slug/'

[taxonomies]
  author = "authors"
  tag = "tags"

[module]
  [module.imports]
    path = "github.com/hugo-mods/icons"

[Params]
  favicon = "images/D2iQ_Logo_Color-RGB.svg"
  # logo = "images/D2iQ_Logo_Color-RGB.svg"

  [Params.social]
    twitter = "d2iq_eng"
