[build]
  publish = "blog/public"
  command = "hugo -s blog --gc --minify"

[build.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  NODE_VERSION = "18.4.0"
  NODE_ENV = "development"
